### ISSUE TITLE
ICarl seq-tinyimg accuracy

### ISSUE THREAD

**Issue by gab709** [aimagelab/mammoth#10]
Hi!
I have a question about the results reported in the paper "Dark Experience for General Continual Learning: a Strong, Simple Baseline"
When I run:
 python ./utils/main.py --model=icarl --dataset=seq-tinyimg --load_best_args --buffer_size=200
the accuracy is around 14% but in the paper the accuracy is around 7%. Have I done something wrong?
Thank you in advance.

**Comment by mbosc** [comment]
Nothing wrong on your side. A previous issue made us find a bug in our code, so we updated our iCarl implementation consequently.

https://github.com/aimagelab/mammoth/issues/3

**Comment by gab709** [comment]
> Nothing wrong on your side. A previous issue made us find a bug in our code, so we updated our iCarl implementation consequently.
> 
> #3

Thank you for your reply!
