### ISSUE TITLE
Gradients of fc1.weight are always zero during the training

### ISSUE THREAD

**Issue by shafeef901** [aimagelab/mammoth#11]
How to reproduce?
Add the following line of code in `line 107` of `training.py` to view the gradient values stored in the parameters of the fc1 layer  after each task. Only bias is being updated.

```
for name, param in model.named_parameters():
    if 'net.fc1' in name:
        print(name, param.grad) 
```

Test script on seq-mnist dataset using der model
`python3 utils/main.py --model der --dataset seq-mnist  --lr 0.03 --batch_size=16 --n_epochs=1 --buffer_size=500 --minibatch_size=16 --alpha=0.1
`
Also tested on derpp, agem, lwf models and on rot-mnist dataset.

**Comment by mbosc** [comment]
Hi there, I tried with the same exact test script you provide and I can confirm that it is non-zero for me!
