### ISSUE TITLE
Mask shape error in xder code implementation

### ISSUE THREAD

**Issue by oyt9306** [aimagelab/mammoth#12]
Hello. Thank you for your recent work and for sharing xder code. 

While I tried to reproduce your work on my one, I encountered a troublesome as follows. 

------------------
File ".../models/xder.py", line 143, in update_logits
    gt_values = old[torch.arange(len(gt)), gt]
IndexError: The shape of the mask [32] at index 0 does not match the shape of the indexed tensor [32, 10] at index 1

Have you ever met such problem? I'd like to ask you how to fix it. Thank you.

**Comment by mbosc** [comment]
Hello there,

I'm gonna need some more details to assess what's happening. (i) What dataset are you using? (is it one of ours?) (ii) what shape is the input tensor of the observe function?

**Comment by oyt9306** [comment]
Thank you for your quick response. For detail, (i) I using custom dataset, (2)

**Comment by oyt9306** [comment]
Thank you for your quick replying. First of all, I tried to run this code for a custom dataset with some modifications. After I examined the code with the cifar-100 dataset, the existing code works well with no troubleshooting. I will update the comment later if I meet the same problem after I look into the code. Thank you :D

**Comment by mbosc** [comment]
Ok, great!

Let me know if you have any trouble.
