### ISSUE TITLE
question for models

### ISSUE THREAD

**Issue by gydpku** [aimagelab/mammoth#2]
Sorry, but I cannot find the dir 'models' in models/__init__.py, and then I cannot run main.py. Is it exists in the previous version?

**Comment by mbosc** [comment]
Hi there. Our relative import paths assume that main should be launched from the project root directory. You should start from the root mammoth folder and then run main as `python utils/main.py`. By running it like this, everything should work. 
Also make sure that the mammoth root directory is in your PYTHONPATH env variable.
