### ISSUE TITLE
Training using ImageNet as First Task and CUB dataset as second Task

### ISSUE THREAD

**Issue by MagicHealer** [aimagelab/mammoth#23]
Is it possible for me to train a continual learning using LwF using Imagenet as initial task and CUB dataset as Second task?

**Comment by loribonna** [comment]
Hi @MagicHealer , unfortunately it is not implemented as of now. 
The closest thing you might find in [twf](https://github.com/mbosc/twf) is the possibility to use imagenet as pretrain and then proceed with train incrementally on CUB200 (with the 200 classes splitted over 10 tasks).

Best, Lorenzo
