### ISSUE TITLE
GEM: add_data to buffer

### ISSUE THREAD

**Issue by tunglamlqddb** [aimagelab/mammoth#26]
https://github.com/aimagelab/mammoth/blob/f3effb9dc2098c0463d214c4f8e5e69f38517e13/models/gem.py#L126

Dear authors,
This part where you add data to buffer in GEM is probably wrong because size of task_labels should be equal to that of examples, but not 'samples_per_task'.
Thank you for revising this.

**Comment by loribonna** [comment]
Hi @tunglamlqddb , this is now fixed in the new version. 
It didn't really affect performance but it was defenately wrong.
