### ISSUE TITLE
error of pnn

### ISSUE THREAD

**Issue by marksheng00** [aimagelab/mammoth#27]
(base) root@marksheng-jgdgkqoauw1k-main:/openbayes/home/mammoth# python ./utils/main.py --model pnn --dataset seq-cifar100  --lr 0.001
Warning: GEM and A-GEM cannot be used on Windows (quadprog required)
Namespace(batch_size=32, conf_host='marksheng-jgdgkqoauw1k-main', conf_jobnum='38cff68f-3a64-41c9-a4e7-be660f81e47d', conf_timestamp='2023-06-16 19:04:08.766651', dataset='seq-cifar100', debug_mode=0, disable_log=0, distributed='no', ignore_other_metrics=0, lr=0.001, model='pnn', n_epochs=50, non_verbose=0, notes=None, nowand=0, optim_mom=0.0, optim_nesterov=0, optim_wd=0.0, seed=None, validation=0, wandb_entity='regaz', wandb_project='mammoth')
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose "Don't visualize my results"
wandb: Tracking run with wandb version 0.15.4
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
wandb: WARNING URL not available in offline run

[ 06-16 | 19:14 ] Task 1 | epoch 49: |██████████████████████████████████████████████████| 384.12 ep/h | loss: 0.38812339 |
Accuracy for 1 task(s):          [Class-IL]: 0.0 %       [Task-IL]: 73.4 %

[ 06-16 | 19:23 ] Task 2 | epoch 49: |██████████████████████████████████████████████████| 376.43 ep/h | loss: 0.80489624 |
Accuracy for 2 task(s):          [Class-IL]: 0.0 %       [Task-IL]: 69.05 %

[ 06-16 | 19:33 ] Task 3 | epoch 49: |██████████████████████████████████████████████████| 324.83 ep/h | loss: 0.40649256 |
Accuracy for 3 task(s):          [Class-IL]: 0.0 %       [Task-IL]: 69.1 %

[ 06-16 | 19:44 ] Task 4 | epoch 49: |██████████████████████████████████████████████████| 290.67 ep/h | loss: 1.19920611 |
Accuracy for 4 task(s):          [Class-IL]: 0.0 %       [Task-IL]: 68.95 %

[ 06-16 | 19:57 ] Task 5 | epoch 49: |██████████████████████████████████████████████████| 255.23 ep/h | loss: 1.46435463 |
Accuracy for 5 task(s):          [Class-IL]: 0.0 %       [Task-IL]: 62.86 %

Traceback (most recent call last):
  File "./utils/main.py", line 138, in <module>
    main()
  File "./utils/main.py", line 131, in main
    train(model, dataset, args)
  File "/output/mammoth/utils/training.py", line 117, in train
    accs = evaluate(model, dataset, last=True)
  File "/output/mammoth/utils/training.py", line 58, in evaluate
    outputs = model(inputs, k)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/output/mammoth/models/pnn.py", line 65, in forward
    self.nets[task_label].to(self.device)
IndexError: list index out of range
wandb: Waiting for W&B process to finish... (failed 1).
wandb: 
wandb: Run history:
wandb:     RESULT_class_acc_0 ▁▁▁▁▁
wandb:     RESULT_class_acc_1 ▁▁▁▁
wandb:     RESULT_class_acc_2 ▁▁▁
wandb:     RESULT_class_acc_3 ▁▁
wandb:     RESULT_class_acc_4 ▁
wandb: RESULT_class_mean_accs ▁▁▁▁▁
wandb:      RESULT_task_acc_0 ▁▁▁▁▁
wandb:      RESULT_task_acc_1 ▁▁▁▁
wandb:      RESULT_task_acc_2 ▁▁▁
wandb:      RESULT_task_acc_3 ▁▁
wandb:      RESULT_task_acc_4 ▁
wandb:  RESULT_task_mean_accs █▅▅▅▁
wandb: 
wandb: Run summary:
wandb:     RESULT_class_acc_0 0
wandb:     RESULT_class_acc_1 0
wandb:     RESULT_class_acc_2 0
wandb:     RESULT_class_acc_3 0
wandb:     RESULT_class_acc_4 0
wandb: RESULT_class_mean_accs 0.0
wandb:      RESULT_task_acc_0 73.4
wandb:      RESULT_task_acc_1 64.7
wandb:      RESULT_task_acc_2 69.2
wandb:      RESULT_task_acc_3 68.5
wandb:      RESULT_task_acc_4 38.5
wandb:  RESULT_task_mean_accs 62.86
wandb: 
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /output/mammoth/wandb/offline-run-20230616_190446-lx8vos0z
wandb: Find logs at: ./wandb/offline-run-20230616_190446-lx8vos0z/logs

**Comment by marksheng00** [comment]
@JosephKJ @baraldilorenzo @mbosc @loribonna

**Comment by loribonna** [comment]
Hi @marksheng00 , we designed PNN to work only on small datasets since it requires a massive amount of memory as tasks go on. This however is fixed in the new version of Mammoth.
