### ISSUE TITLE
the layer of the feature of resnet missed relu?

### ISSUE THREAD

**Issue by Zhen-Zohn-WANG** [aimagelab/mammoth#3]
Thank you for your wonderful work.

I wonder did the layer of the feature of resnet miss relu?

```
        self._features = nn.Sequential(self.conv1,
                                       self.bn1,
                                       self.layer1,
                                       self.layer2,
                                       self.layer3,
                                       self.layer4
                                       )
```
But the forward of model has relu.

**Comment by mbosc** [comment]
Thank you very much for your help!
Yes, we have a relu missing in the feature function for ResNet18. We expect that this should give some boost in performance to the affected methods (i.e. iCaRL, LwF and HAL). We will re-run our experiments and push both an updated version of our code and our results soon.
