### ISSUE TITLE
Could you offer the best values of the necessary parameters of der?

### ISSUE THREAD

**Issue by Humothetrader** [aimagelab/mammoth#33]
Sorry to bother you. I didn't found the best values of alpha, beta and learning_rate in the paper and the code, and the code need me to set these values by myself, so could you please offer the best values of the necessary parameters of der (or are they already there now)? I cannot get the same performance on cifar10 500buffer as table2 in the paper with optionally setting the values of alpha, beta and learning_rate, thank you.

**Comment by mbosc** [comment]
No problem!

You can use the --load_best_args flag with seq-cifar-10 as dataset and specifying the buffer size to load the best arguments, which should be.

{'lr': 0.03,
  'minibatch_size': 32,
  'alpha': 0.3,
  'batch_size': 32,
  'n_epochs': 50},
  
  for der and
  
{'lr': 0.03,
  'minibatch_size': 32,
  'alpha': 0.2,
  'beta': 0.5,
  'batch_size': 32,
  'n_epochs': 50},

for der++

These are the same arguments that you can find on page 21 and following of our manuscript https://arxiv.org/pdf/2004.07211.pdf
