### ISSUE TITLE
Question regarding EWC_ON

### ISSUE THREAD

**Issue by bhat-prashant** [aimagelab/mammoth#9]
Dear authors, 
I reciprocated your results on ewc_on using your code. I could get 19.49% on CIFAR-10(same as yours). However, I see that catastrophic forgetting is actually catastrophic i.e performance on previous tasks hit zero once the model is past those tasks. Please see graph attached for more info. 
acc_mean:
![acc_mean](https://user-images.githubusercontent.com/56539375/129031826-dc7e8d7a-23a9-4983-b138-275ac3190aa5.png)

acc_task01:
![acc_task01](https://user-images.githubusercontent.com/56539375/129031823-fde3829f-9b4e-44b7-92a6-75a59aff0e33.png)

acc_task02:
![acc_task02](https://user-images.githubusercontent.com/56539375/129031821-90634ac4-1209-46c2-b7ae-c498fb6ce6a9.png)

Please let me know whether this is due to the implementation or is it a proper behavior of ewc_on.

**Comment by mbosc** [comment]
Hello there,

Yes, the result you obtain is in line with our experience: ewc online (actually, most regularisation methods for that matter) struggles terribly in the class-il setting. Bear in mind that ewc online is designed for the task-il setting: it is not designed to sensibly combine the tasks it learns separately in a unified classifier.

If you're looking for a valid baseline in the class-il setting, we'd recommend using a rehearsal method instead (e.g. ER).

**Comment by MayYoY** [comment]
> Hello there,
> 
> Yes, the result you obtain is in line with our experience: ewc online struggles terribly in the class-il setting (actually, most regularisation methods do for that matter) . Bear in mind that ewc online is designed for the task-il setting: it is not designed to sensibly combine the tasks it learns separately in a unified classifier.
> 
> If you're looking for a valid baseline in the class-il setting, we'd recommend using a rehearsal method instead (e.g. ER).
Hello, could you please point out which paper states that ewc is not suitable for class-il setting? Thank you!
